package sdl

// #include <SDL2/SDL.h>
import "C"

const K_SCANCODE_MASK = 1 << 30

const (
	K_UNKNOWN = 0

	K_RETURN     = '\r'
	K_ESCAPE     = '\033'
	K_BACKSPACE  = '\b'
	K_TAB        = '\t'
	K_SPACE      = ' '
	K_EXCLAIM    = '!'
	K_QUOTEDBL   = '"'
	K_HASH       = '#'
	K_PERCENT    = '%'
	K_DOLLAR     = '$'
	K_AMPERSAND  = '&'
	K_QUOTE      = '\''
	K_LEFTPAREN  = '('
	K_RIGHTPAREN = ')'
	K_ASTERISK   = '*'
	K_PLUS       = '+'
	K_COMMA      = ','
	K_MINUS      = '-'
	K_PERIOD     = '.'
	K_SLASH      = '/'
	K_0          = '0'
	K_1          = '1'
	K_2          = '2'
	K_3          = '3'
	K_4          = '4'
	K_5          = '5'
	K_6          = '6'
	K_7          = '7'
	K_8          = '8'
	K_9          = '9'
	K_COLON      = ':'
	K_SEMICOLON  = ';'
	K_LESS       = '<'
	K_EQUALS     = '='
	K_GREATER    = '>'
	K_QUESTION   = '?'
	K_AT         = '@'
	/*
	   Skip uppercase letters
	*/
	K_LEFTBRACKET  = '['
	K_BACKSLASH    = '\\'
	K_RIGHTBRACKET = ']'
	K_CARET        = '^'
	K_UNDERSCORE   = '_'
	K_BACKQUOTE    = '`'
	K_a            = 'a'
	K_b            = 'b'
	K_c            = 'c'
	K_d            = 'd'
	K_e            = 'e'
	K_f            = 'f'
	K_g            = 'g'
	K_h            = 'h'
	K_i            = 'i'
	K_j            = 'j'
	K_k            = 'k'
	K_l            = 'l'
	K_m            = 'm'
	K_n            = 'n'
	K_o            = 'o'
	K_p            = 'p'
	K_q            = 'q'
	K_r            = 'r'
	K_s            = 's'
	K_t            = 't'
	K_u            = 'u'
	K_v            = 'v'
	K_w            = 'w'
	K_x            = 'x'
	K_y            = 'y'
	K_z            = 'z'

	K_CAPSLOCK = SCANCODE_CAPSLOCK | K_SCANCODE_MASK

	K_F1  = SCANCODE_F1 | K_SCANCODE_MASK
	K_F2  = SCANCODE_F2 | K_SCANCODE_MASK
	K_F3  = SCANCODE_F3 | K_SCANCODE_MASK
	K_F4  = SCANCODE_F4 | K_SCANCODE_MASK
	K_F5  = SCANCODE_F5 | K_SCANCODE_MASK
	K_F6  = SCANCODE_F6 | K_SCANCODE_MASK
	K_F7  = SCANCODE_F7 | K_SCANCODE_MASK
	K_F8  = SCANCODE_F8 | K_SCANCODE_MASK
	K_F9  = SCANCODE_F9 | K_SCANCODE_MASK
	K_F10 = SCANCODE_F10 | K_SCANCODE_MASK
	K_F11 = SCANCODE_F11 | K_SCANCODE_MASK
	K_F12 = SCANCODE_F12 | K_SCANCODE_MASK

	K_PRINTSCREEN = SCANCODE_PRINTSCREEN | K_SCANCODE_MASK
	K_SCROLLLOCK  = SCANCODE_SCROLLLOCK | K_SCANCODE_MASK
	K_PAUSE       = SCANCODE_PAUSE | K_SCANCODE_MASK
	K_INSERT      = SCANCODE_INSERT | K_SCANCODE_MASK
	K_HOME        = SCANCODE_HOME | K_SCANCODE_MASK
	K_PAGEUP      = SCANCODE_PAGEUP | K_SCANCODE_MASK
	K_DELETE      = '\177'
	K_END         = SCANCODE_END | K_SCANCODE_MASK
	K_PAGEDOWN    = SCANCODE_PAGEDOWN | K_SCANCODE_MASK
	K_RIGHT       = SCANCODE_RIGHT | K_SCANCODE_MASK
	K_LEFT        = SCANCODE_LEFT | K_SCANCODE_MASK
	K_DOWN        = SCANCODE_DOWN | K_SCANCODE_MASK
	K_UP          = SCANCODE_UP | K_SCANCODE_MASK

	K_NUMLOCKCLEAR = SCANCODE_NUMLOCKCLEAR | K_SCANCODE_MASK
	K_KP_DIVIDE    = SCANCODE_KP_DIVIDE | K_SCANCODE_MASK
	K_KP_MULTIPLY  = SCANCODE_KP_MULTIPLY | K_SCANCODE_MASK
	K_KP_MINUS     = SCANCODE_KP_MINUS | K_SCANCODE_MASK
	K_KP_PLUS      = SCANCODE_KP_PLUS | K_SCANCODE_MASK
	K_KP_ENTER     = SCANCODE_KP_ENTER | K_SCANCODE_MASK
	K_KP_1         = SCANCODE_KP_1 | K_SCANCODE_MASK
	K_KP_2         = SCANCODE_KP_2 | K_SCANCODE_MASK
	K_KP_3         = SCANCODE_KP_3 | K_SCANCODE_MASK
	K_KP_4         = SCANCODE_KP_4 | K_SCANCODE_MASK
	K_KP_5         = SCANCODE_KP_5 | K_SCANCODE_MASK
	K_KP_6         = SCANCODE_KP_6 | K_SCANCODE_MASK
	K_KP_7         = SCANCODE_KP_7 | K_SCANCODE_MASK
	K_KP_8         = SCANCODE_KP_8 | K_SCANCODE_MASK
	K_KP_9         = SCANCODE_KP_9 | K_SCANCODE_MASK
	K_KP_0         = SCANCODE_KP_0 | K_SCANCODE_MASK
	K_KP_PERIOD    = SCANCODE_KP_PERIOD | K_SCANCODE_MASK

	K_APPLICATION    = SCANCODE_APPLICATION | K_SCANCODE_MASK
	K_POWER          = SCANCODE_POWER | K_SCANCODE_MASK
	K_KP_EQUALS      = SCANCODE_KP_EQUALS | K_SCANCODE_MASK
	K_F13            = SCANCODE_F13 | K_SCANCODE_MASK
	K_F14            = SCANCODE_F14 | K_SCANCODE_MASK
	K_F15            = SCANCODE_F15 | K_SCANCODE_MASK
	K_F16            = SCANCODE_F16 | K_SCANCODE_MASK
	K_F17            = SCANCODE_F17 | K_SCANCODE_MASK
	K_F18            = SCANCODE_F18 | K_SCANCODE_MASK
	K_F19            = SCANCODE_F19 | K_SCANCODE_MASK
	K_F20            = SCANCODE_F20 | K_SCANCODE_MASK
	K_F21            = SCANCODE_F21 | K_SCANCODE_MASK
	K_F22            = SCANCODE_F22 | K_SCANCODE_MASK
	K_F23            = SCANCODE_F23 | K_SCANCODE_MASK
	K_F24            = SCANCODE_F24 | K_SCANCODE_MASK
	K_EXECUTE        = SCANCODE_EXECUTE | K_SCANCODE_MASK
	K_HELP           = SCANCODE_HELP | K_SCANCODE_MASK
	K_MENU           = SCANCODE_MENU | K_SCANCODE_MASK
	K_SELECT         = SCANCODE_SELECT | K_SCANCODE_MASK
	K_STOP           = SCANCODE_STOP | K_SCANCODE_MASK
	K_AGAIN          = SCANCODE_AGAIN | K_SCANCODE_MASK
	K_UNDO           = SCANCODE_UNDO | K_SCANCODE_MASK
	K_CUT            = SCANCODE_CUT | K_SCANCODE_MASK
	K_COPY           = SCANCODE_COPY | K_SCANCODE_MASK
	K_PASTE          = SCANCODE_PASTE | K_SCANCODE_MASK
	K_FIND           = SCANCODE_FIND | K_SCANCODE_MASK
	K_MUTE           = SCANCODE_MUTE | K_SCANCODE_MASK
	K_VOLUMEUP       = SCANCODE_VOLUMEUP | K_SCANCODE_MASK
	K_VOLUMEDOWN     = SCANCODE_VOLUMEDOWN | K_SCANCODE_MASK
	K_KP_COMMA       = SCANCODE_KP_COMMA | K_SCANCODE_MASK
	K_KP_EQUALSAS400 = SCANCODE_KP_EQUALSAS400 | K_SCANCODE_MASK

	K_ALTERASE   = SCANCODE_ALTERASE | K_SCANCODE_MASK
	K_SYSREQ     = SCANCODE_SYSREQ | K_SCANCODE_MASK
	K_CANCEL     = SCANCODE_CANCEL | K_SCANCODE_MASK
	K_CLEAR      = SCANCODE_CLEAR | K_SCANCODE_MASK
	K_PRIOR      = SCANCODE_PRIOR | K_SCANCODE_MASK
	K_RETURN2    = SCANCODE_RETURN2 | K_SCANCODE_MASK
	K_SEPARATOR  = SCANCODE_SEPARATOR | K_SCANCODE_MASK
	K_OUT        = SCANCODE_OUT | K_SCANCODE_MASK
	K_OPER       = SCANCODE_OPER | K_SCANCODE_MASK
	K_CLEARAGAIN = SCANCODE_CLEARAGAIN | K_SCANCODE_MASK
	K_CRSEL      = SCANCODE_CRSEL | K_SCANCODE_MASK
	K_EXSEL      = SCANCODE_EXSEL | K_SCANCODE_MASK

	K_KP_00              = SCANCODE_KP_00 | K_SCANCODE_MASK
	K_KP_000             = SCANCODE_KP_000 | K_SCANCODE_MASK
	K_THOUSANDSSEPARATOR = SCANCODE_THOUSANDSSEPARATOR | K_SCANCODE_MASK
	K_DECIMALSEPARATOR   = SCANCODE_DECIMALSEPARATOR | K_SCANCODE_MASK
	K_CURRENCYUNIT       = SCANCODE_CURRENCYUNIT | K_SCANCODE_MASK
	K_CURRENCYSUBUNIT    = SCANCODE_CURRENCYSUBUNIT | K_SCANCODE_MASK
	K_KP_LEFTPAREN       = SCANCODE_KP_LEFTPAREN | K_SCANCODE_MASK
	K_KP_RIGHTPAREN      = SCANCODE_KP_RIGHTPAREN | K_SCANCODE_MASK
	K_KP_LEFTBRACE       = SCANCODE_KP_LEFTBRACE | K_SCANCODE_MASK
	K_KP_RIGHTBRACE      = SCANCODE_KP_RIGHTBRACE | K_SCANCODE_MASK
	K_KP_TAB             = SCANCODE_KP_TAB | K_SCANCODE_MASK
	K_KP_BACKSPACE       = SCANCODE_KP_BACKSPACE | K_SCANCODE_MASK
	K_KP_A               = SCANCODE_KP_A | K_SCANCODE_MASK
	K_KP_B               = SCANCODE_KP_B | K_SCANCODE_MASK
	K_KP_C               = SCANCODE_KP_C | K_SCANCODE_MASK
	K_KP_D               = SCANCODE_KP_D | K_SCANCODE_MASK
	K_KP_E               = SCANCODE_KP_E | K_SCANCODE_MASK
	K_KP_F               = SCANCODE_KP_F | K_SCANCODE_MASK
	K_KP_XOR             = SCANCODE_KP_XOR | K_SCANCODE_MASK
	K_KP_POWER           = SCANCODE_KP_POWER | K_SCANCODE_MASK
	K_KP_PERCENT         = SCANCODE_KP_PERCENT | K_SCANCODE_MASK
	K_KP_LESS            = SCANCODE_KP_LESS | K_SCANCODE_MASK
	K_KP_GREATER         = SCANCODE_KP_GREATER | K_SCANCODE_MASK
	K_KP_AMPERSAND       = SCANCODE_KP_AMPERSAND | K_SCANCODE_MASK
	K_KP_DBLAMPERSAND    = SCANCODE_KP_DBLAMPERSAND | K_SCANCODE_MASK
	K_KP_VERTICALBAR     = SCANCODE_KP_VERTICALBAR | K_SCANCODE_MASK
	K_KP_DBLVERTICALBAR  = SCANCODE_KP_DBLVERTICALBAR | K_SCANCODE_MASK
	K_KP_COLON           = SCANCODE_KP_COLON | K_SCANCODE_MASK
	K_KP_HASH            = SCANCODE_KP_HASH | K_SCANCODE_MASK
	K_KP_SPACE           = SCANCODE_KP_SPACE | K_SCANCODE_MASK
	K_KP_AT              = SCANCODE_KP_AT | K_SCANCODE_MASK
	K_KP_EXCLAM          = SCANCODE_KP_EXCLAM | K_SCANCODE_MASK
	K_KP_MEMSTORE        = SCANCODE_KP_MEMSTORE | K_SCANCODE_MASK
	K_KP_MEMRECALL       = SCANCODE_KP_MEMRECALL | K_SCANCODE_MASK
	K_KP_MEMCLEAR        = SCANCODE_KP_MEMCLEAR | K_SCANCODE_MASK
	K_KP_MEMADD          = SCANCODE_KP_MEMADD | K_SCANCODE_MASK
	K_KP_MEMSUBTRACT     = SCANCODE_KP_MEMSUBTRACT | K_SCANCODE_MASK
	K_KP_MEMMULTIPLY     = SCANCODE_KP_MEMMULTIPLY | K_SCANCODE_MASK
	K_KP_MEMDIVIDE       = SCANCODE_KP_MEMDIVIDE | K_SCANCODE_MASK
	K_KP_PLUSMINUS       = SCANCODE_KP_PLUSMINUS | K_SCANCODE_MASK
	K_KP_CLEAR           = SCANCODE_KP_CLEAR | K_SCANCODE_MASK
	K_KP_CLEARENTRY      = SCANCODE_KP_CLEARENTRY | K_SCANCODE_MASK
	K_KP_BINARY          = SCANCODE_KP_BINARY | K_SCANCODE_MASK
	K_KP_OCTAL           = SCANCODE_KP_OCTAL | K_SCANCODE_MASK
	K_KP_DECIMAL         = SCANCODE_KP_DECIMAL | K_SCANCODE_MASK
	K_KP_HEXADECIMAL     = SCANCODE_KP_HEXADECIMAL | K_SCANCODE_MASK

	K_LCTRL  = SCANCODE_LCTRL | K_SCANCODE_MASK
	K_LSHIFT = SCANCODE_LSHIFT | K_SCANCODE_MASK
	K_LALT   = SCANCODE_LALT | K_SCANCODE_MASK
	K_LGUI   = SCANCODE_LGUI | K_SCANCODE_MASK
	K_RCTRL  = SCANCODE_RCTRL | K_SCANCODE_MASK
	K_RSHIFT = SCANCODE_RSHIFT | K_SCANCODE_MASK
	K_RALT   = SCANCODE_RALT | K_SCANCODE_MASK
	K_RGUI   = SCANCODE_RGUI | K_SCANCODE_MASK

	K_MODE = SCANCODE_MODE | K_SCANCODE_MASK

	K_AUDIONEXT    = SCANCODE_AUDIONEXT | K_SCANCODE_MASK
	K_AUDIOPREV    = SCANCODE_AUDIOPREV | K_SCANCODE_MASK
	K_AUDIOSTOP    = SCANCODE_AUDIOSTOP | K_SCANCODE_MASK
	K_AUDIOPLAY    = SCANCODE_AUDIOPLAY | K_SCANCODE_MASK
	K_AUDIOMUTE    = SCANCODE_AUDIOMUTE | K_SCANCODE_MASK
	K_MEDIASELECT  = SCANCODE_MEDIASELECT | K_SCANCODE_MASK
	K_WWW          = SCANCODE_WWW | K_SCANCODE_MASK
	K_MAIL         = SCANCODE_MAIL | K_SCANCODE_MASK
	K_CALCULATOR   = SCANCODE_CALCULATOR | K_SCANCODE_MASK
	K_COMPUTER     = SCANCODE_COMPUTER | K_SCANCODE_MASK
	K_AC_SEARCH    = SCANCODE_AC_SEARCH | K_SCANCODE_MASK
	K_AC_HOME      = SCANCODE_AC_HOME | K_SCANCODE_MASK
	K_AC_BACK      = SCANCODE_AC_BACK | K_SCANCODE_MASK
	K_AC_FORWARD   = SCANCODE_AC_FORWARD | K_SCANCODE_MASK
	K_AC_STOP      = SCANCODE_AC_STOP | K_SCANCODE_MASK
	K_AC_REFRESH   = SCANCODE_AC_REFRESH | K_SCANCODE_MASK
	K_AC_BOOKMARKS = SCANCODE_AC_BOOKMARKS | K_SCANCODE_MASK

	K_BRIGHTNESSDOWN = SCANCODE_BRIGHTNESSDOWN | K_SCANCODE_MASK
	K_BRIGHTNESSUP   = SCANCODE_BRIGHTNESSUP | K_SCANCODE_MASK
	K_DISPLAYSWITCH  = SCANCODE_DISPLAYSWITCH | K_SCANCODE_MASK
	K_KBDILLUMTOGGLE = SCANCODE_KBDILLUMTOGGLE | K_SCANCODE_MASK
	K_KBDILLUMDOWN   = SCANCODE_KBDILLUMDOWN | K_SCANCODE_MASK
	K_KBDILLUMUP     = SCANCODE_KBDILLUMUP | K_SCANCODE_MASK
	K_EJECT          = SCANCODE_EJECT | K_SCANCODE_MASK
	K_SLEEP          = SCANCODE_SLEEP | K_SCANCODE_MASK
)

const (
	KMOD_NONE     = 0x0000
	KMOD_LSHIFT   = 0x0001
	KMOD_RSHIFT   = 0x0002
	KMOD_LCTRL    = 0x0040
	KMOD_RCTRL    = 0x0080
	KMOD_LALT     = 0x0100
	KMOD_RALT     = 0x0200
	KMOD_LGUI     = 0x0400
	KMOD_RGUI     = 0x0800
	KMOD_NUM      = 0x1000
	KMOD_CAPS     = 0x2000
	KMOD_MODE     = 0x4000
	KMOD_RESERVED = 0x8000
)

const (
	KMOD_CTRL  = KMOD_LCTRL | KMOD_RCTRL
	KMOD_SHIFT = KMOD_LSHIFT | KMOD_RSHIFT
	KMOD_ALT   = KMOD_LALT | KMOD_RALT
	KMOD_GUI   = KMOD_LGUI | KMOD_RGUI
)

type Keycode C.SDL_Keycode
type Keymod C.SDL_Keymod

func (code Keycode) c() C.SDL_Keycode {
    return C.SDL_Keycode(code)
}

func (mod Keymod) c() C.SDL_Keymod {
    return C.SDL_Keymod(mod)
}
